<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <IsMac>false</IsMac>
        <IsMac Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))'">true</IsMac>

        <!-- Windows: fill in your Duckov install path -->
        <DuckovPath>E:\Program Files (x86)\Steam\steamapps\common\Escape from Duckov</DuckovPath>

        <!-- Mac -->
        <DuckovPath Condition="'$(IsMac)'">$(HOME)/Library/Application Support/Steam/steamapps/common/Escape from Duckov</DuckovPath>

        <SubPath>\Duckov_Data\Managed\</SubPath>
        <SubPath Condition="'$(IsMac)'">/Duckov.app/Contents/Resources/Data/Managed/</SubPath>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="$(DuckovPath)$(SubPath)TeamSoda.*">
          <Private>False</Private>
        </Reference>
        <Reference Include="$(DuckovPath)$(SubPath)ItemStatsSystem.dll">
          <Private>False</Private>
        </Reference>
        <Reference Include="$(DuckovPath)$(SubPath)SodaLocalization.dll">
          <Private>False</Private>
        </Reference>
        <Reference Include="$(DuckovPath)$(SubPath)Unity*">
          <Private>False</Private>
        </Reference>
    </ItemGroup>
</Project>
